// <auto-generated />
namespace HappyDogShow.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BreedClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BreedClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "201912211826580_BreedClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
