// <auto-generated />
namespace HappyDogShow.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ShowBreedJudges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShowBreedJudges));
        
        string IMigrationMetadata.Id
        {
            get { return "202001071130313_ShowBreedJudges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
